name: Check for New TypeScript Errors

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - test-action

jobs:
  check-new-tsc-errors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Check for new typescript errors
        uses: ./.github/actions/tsc-check
        with:
          install-command: './.github/actions/setup'
