name: Check for New TypeScript Errors

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - test-action

jobs:
  check-tsc-errors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Fetch branches
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }} ${{ github.head_ref }}:${{ github.head_ref }}

      - name: Extract base branch name
        run: |
          branch=${{ github.base_ref }}
          branch=${branch//\//}  # This removes all slashes from the branch name
          echo "branch=${branch}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout base branch
        run: git checkout ${{ github.base_ref }}

      - name: Install dependencies for base branch
        uses: ./.github/actions/setup

      - name: Generate base branch tsc output
        run: |
          echo "Running tsc"
          npx tsc --noEmit --pretty false --p tsconfig.json 2> base-tsc-output.txt || true
          cat base-tsc-output.txt

      - name: Save base tsc output to temp directory
        run: |
          mkdir -p temp
          mv base-tsc-output.txt temp/base-tsc-output.txt

      - name: Checkout PR branch
        run: git checkout ${{ github.head_ref }}

      - name: Print contents of temp directory
        run: ls -al temp

      - name: Restore base tsc output from temp directory
        run: mv temp/base-tsc-output.txt base-tsc-output.txt

      - name: Print base tsc output
        run: cat base-tsc-output.txt

      - name: Install dependencies for PR branch
        uses: ./.github/actions/setup

      - name: Run tsc on PR branch
        run: |
          npx tsc --noEmit --pretty false --p tsconfig.json > head-tsc-output.txt || true

      - name: Check both tsc outputs exist
        run: |
          if [ ! -f base-tsc-output.txt ]; then
            echo "Base output file not found!"
            exit 1
          fi
          if [ ! -f head-tsc-output.txt ]; then
            echo "PR output file not found!"
            exit 1
          fi

      - name: Compare base errors with PR errors
        run: |
          echo "base"
          cat base-tsc-output.txt

          echo "head"
          cat head-tsc-output.txt

          diff_output=$(diff -u base-tsc-output.txt head-tsc-output.txt | grep -E '^\+' | grep -vE '^\+\+\+|^---')

          if [ -n "$diff_output" ]; then
            echo "New TypeScript errors introduced:"
            echo "$diff_output"
            exit 1
          else
            echo "No new TypeScript errors introduced."
          fi
